stages:
- deploy

frontend:
    stage: deploy
    only:
    - develop
    tags:
    - deploy
    script:
    - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v9.11.1/bin
    - npm install
    - npm run build
    - cp -r dist/* /var/www/$CI_PROJECT_NAME/htdocs/
    cache:
        paths:
        - node_modules/